# Generated by Django 3.1 on 2022-07-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20220704_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
    ]
