# Generated by Django 3.1 on 2022-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20220704_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_end_year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_start_year',
            field=models.DateField(auto_now=True),
        ),
    ]
