# Generated by Django 3.1 on 2022-07-12 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_auto_20220704_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_AdminHOD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_Staffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_Students', to=settings.AUTH_USER_MODEL),
        ),
    ]
