# Generated by Django 3.1 on 2022-05-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('data', models.DateField(auto_now=True)),
                ('image', models.URLField(max_length=1000)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='class_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('data', models.DateField(auto_now=True)),
                ('image', models.URLField(max_length=1000)),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
